site:
  title: Boost.safe_numbers
  start_page: safe_numbers::overview.adoc
content:
  sources:
    - url: ..
      start_path: doc
      branches: HEAD
output:
  dir: html
ui:
  bundle:
    url: https://github.com/boostorg/website-v2-docs/releases/download/ui-master/ui-bundle.zip
  output_dir: safe_numbers/_
